export const NFTs = [
    {
        id: 2,
        name: "Socrates",
        description:
            "250000 AGO \n-20% on transaction fees \n6% Cashback \n7% Referral on INO",
        affiliationLevel1: 7,
        affiliationLevel2: 2,
        fees: 20,
        cashback: 6,
        price: 10000,
        ago: 250000,
    },
    {
        id: 3,
        name: "Plato",
        description:
            "125000 AGO \n-18% on transaction fees \n5% Cashback \n6% Referral on INO",
        affiliationLevel1: 6,
        affiliationLevel2: 2,
        fees: 18,
        cashback: 5,
        price: 5000,
        ago: 12500,
    },
    {
        id: 4,
        name: "Aristotle",
        description:
            "62500 AGO \n-16% on transaction fees \n4% Cashback \n5% Referral on INO",
        affiliationLevel1: 5,
        affiliationLevel2: 2,
        fees: 16,
        cashback: 4,
        price: 2500,
        ago: 62500,
    },
    {
        id: 5,
        name: "Pythagoras",
        description:
            "16667 AGO \n-14% on transaction fees \n3% Cashback \n4% Referral on INO",
        affiliationLevel1: 4,
        affiliationLevel2: 2,
        fees: 14,
        cashback: 3,
        price: 1000,
        ago: 16667,
    },
    {
        id: 6,
        name: "Epicurus",
        description:
            "6250 AGO \n-12% on transaction fees \n2% Cashback \n4% Referral on INO",
        affiliationLevel1: 4,
        affiliationLevel2: 2,
        fees: 12,
        cashback: 2,
        price: 500,
        ago: 6250,
    },
    {
        id: 7,
        name: "Thales",
        description:
            "1250 AGO \n-10% on transaction fees \n1% Cashback \n4% Referral on INO",
        affiliationLevel1: 4,
        affiliationLevel2: 2,
        fees: 10,
        cashback: 1,
        price: 100,
        ago: 1250,
    },
    {
        id: 8,
        name: "Citizen",
        description:
            "1250 AGO \n-10% on transaction fees \n1% Cashback \n4% Referral on INO",
        affiliationLevel1: 3,
        affiliationLevel2: 2,
        fees: 10,
        cashback: 1,
        price: 50,
        ago: 0,
    },
];
